default:
  image:
    name: mitchell3514/flutter@sha256:ea98eeae551eb9180276f445db9f1d0bdd4b95e976a739c11887de2b9f96957c
    entrypoint: [""]
  interruptible: true
  before_script:
    - export PATH="$CI_PROJECT_DIR/.pub-cache/bin:$PATH"

workflow:
  auto_cancel:
    on_new_commit: conservative
    on_job_failure: none
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'

stages:
  - setup
  - analyze
  - test
  - build

variables:
  GIT_DEPTH: "3"
  GIT_CLONE_PATH: "$CI_BUILDS_DIR/$CI_PROJECT_PATH/$CI_COMMIT_SHA"
  PUB_CACHE: "$CI_PROJECT_DIR/.pub-cache"

setup_dependencies:
  stage: setup
  cache:
    key:
      files:
        - pubspec.yaml
        - pubspec.lock
    paths:
      - "$PUB_CACHE"
  script:
    - flutter pub get --enforce-lockfile
    - (flutter pub global deactivate junitreport || true) && flutter pub global activate junitreport
  artifacts:
    name: "dependencies"
    untracked: true
    access: 'none'
    paths:
      - ".pub-cache/"

setup_mocks:
  stage: setup
  variables:
    GIT_STRATEGY: clone
  artifacts:
    name: "mocks"
    access: none
    paths:
      - test/**/*.mocks.dart
  needs:
    - job: setup_dependencies
      artifacts: true
  script:
    - dart run build_runner build --delete-conflicting-outputs

analyze_linting:
  stage: analyze
  script:
    - flutter analyze --no-pub --fatal-infos --fatal-warnings

test_accessibility:
  stage: test
  script:
    - flutter test --no-pub --reporter=failures-only --file-reporter json:coverage/accessibility_tests.json --tags=accessibility
    - flutter pub global run junitreport:tojunit --input coverage/accessibility_tests.json --output coverage/accessibility_tests.xml
  artifacts:
    reports:
      junit: coverage/accessibility_tests.xml
  allow_failure: true

test_widgets:
  stage: test
  script:
    - flutter test --no-pub --coverage --reporter=failures-only --file-reporter json:coverage/widget_tests.json --exclude-tags=accessibility
    - scripts/lcov_to_coverage.sh coverage/lcov.info
    - flutter pub global run junitreport:tojunit --input coverage/widget_tests.json --output coverage/widget_tests.xml
  coverage: '/Coverage: \d+(?:\.\d+)?%/'
  artifacts:
    name: "widget-test-coverage"
    when: always
    expose_as: "Widget test coverage"
    paths:
      - coverage/lcov.info
    reports:
      junit: coverage/widget_tests.xml

build_android:
  image: mitchell3514/flutter@sha256:434b2d3b3e62184f3069fca246723888e6f56d8904516bcdc3e3485de40099d8
  stage: build
  script:
    - flutter pub get --enforce-lockfile
    - flutter build apk --release --no-pub
  dependencies: []
  artifacts:
    name: "android-build-apk"
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 2 mos
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - .gitlab-ci.yml

# Dependency Scanning: https://docs.gitlab.com/ee/user/application_security/dependency_scanning
include:
  - template: Jobs/Dependency-Scanning.v2.gitlab-ci.yml
