default:
  image: mitchell3514/flutter@sha256:ea98eeae551eb9180276f445db9f1d0bdd4b95e976a739c11887de2b9f96957c

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - .gitlab-ci.yml

stages:
  - setup
  - analyze
  - test
  - build

deps:
  stage: setup
  artifacts:
    untracked: true
    access: 'none'
  script:
    - flutter pub get --enforce-lockfile

linting:
  stage: analyze
  script:
    - flutter analyze --no-pub --fatal-infos --fatal-warnings

tests:
  stage: test
  script:
    - flutter test --no-pub --coverage --reporter=failures-only --file-reporter json:coverage/tests.json
    - scripts/lcov_to_coverage.sh coverage/lcov.info
    - flutter pub global activate junitreport
    - flutter pub global run junitreport:tojunit --input coverage/tests.json --output coverage/tests.xml
  coverage: '/Coverage: \d+(?:\.\d+)?%/'
  artifacts:
    when: always
    paths:
      - coverage/tests.xml
      - coverage/lcov.info
    reports:
      junit: coverage/tests.xml

build_android:
  image: mitchell3514/flutter@sha256:434b2d3b3e62184f3069fca246723888e6f56d8904516bcdc3e3485de40099d8
  stage: build
  script:
    - flutter pub get --enforce-lockfile
    - flutter build apk --release --no-pub
  dependencies: []
  artifacts:
    name: "android-build-apk"
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 2 mos
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - .gitlab-ci.yml
