# Dependency Scanning: https://docs.gitlab.com/ee/user/application_security/dependency_scanning
include:
  - template: Jobs/Dependency-Scanning.v2.gitlab-ci.yml

default:
  image:
    name: "$CI_IMAGE"
  retry:
    max: 2
    exit_codes: 128

workflow:
  auto_cancel:
    on_new_commit: interruptible
    on_job_failure: none
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'

stages:
  - setup
  - analyze
  - test
  - build
  - release

variables:
  GIT_DEPTH: "3"
  CI_IMAGE_TAG_FILES: "Dockerfile pubspec.yaml pubspec.lock"

setup_image:
  stage: setup
  image: docker:20.10.21
  services:
    - name: docker:20.10.21-dind
      command: ["--mtu", "1400", "--registry-mirror", "http://gitlab.ewi.tudelft.nl:4242"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_BUILDKIT: "1"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - CI_IMAGE_TAG=$(cat $CI_IMAGE_TAG_FILES 2>/dev/null | sha256sum | cut -c1-12)
    - CI_IMAGE="$CI_REGISTRY_IMAGE:$CI_IMAGE_TAG"
  script:
    - if ! docker manifest inspect "$CI_IMAGE" >/dev/null 2>&1; then docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from "${CI_REGISTRY}:latest" --tag "$CI_IMAGE" --tag "${CI_REGISTRY_IMAGE}:latest" --file Dockerfile --target ci . && docker push "$CI_IMAGE" && docker push "${CI_REGISTRY_IMAGE}:latest"; fi
    - echo "CI_IMAGE=$CI_IMAGE" > ci_image.env
  artifacts:
    reports:
      dotenv: ci_image.env

setup_translations:
  interruptible: true
  stage: setup
  needs: [setup_image]
  image: "$CI_IMAGE"
  artifacts:
    name: "setup_translations"
    access: 'none'
    paths:
      - lib/l10n/generated/
  script:
    - flutter gen-l10n

setup_mocks:
  stage: setup
  needs: [setup_image]
  image: "$CI_IMAGE"
  cache:
    key: "setup_mocks"
    paths:
      - .dart_tool/
  artifacts:
    name: "setup_mocks"
    access: 'none'
    paths:
      - .dart_tool/
      - test/**/*.mocks.dart
  script:
    - dart run build_runner build

analyze_linting:
  interruptible: true
  stage: analyze
  script:
    - flutter analyze --no-pub --machine --fatal-infos --fatal-warnings

test_accessibility:
  interruptible: true
  stage: test
  script:
    - flutter test --no-pub --reporter=failures-only --file-reporter json:coverage/accessibility_tests.json --tags=accessibility
    - flutter pub global run junitreport:tojunit --input coverage/accessibility_tests.json --output coverage/accessibility_tests.xml
  artifacts:
    reports:
      junit: coverage/accessibility_tests.xml
  allow_failure: true

test_regression:
  interruptible: true
  stage: test
  script:
    - flutter test --no-pub --reporter=failures-only --file-reporter json:coverage/regression_tests.json --tags=snaptest
    - flutter pub global run junitreport:tojunit --input coverage/regression_tests.json --output coverage/regression_tests.xml
  artifacts:
    name: "test_regression_results"
    when: on_failure
    paths:
      - test/**/failures/*
    expire_in: 1 week
    reports:
      junit: coverage/regression_tests.xml
  allow_failure: true

test_widgets:
  interruptible: true
  stage: test
  script:
    - flutter test --no-pub --coverage --reporter=failures-only --file-reporter json:coverage/widget_tests.json --exclude-tags=accessibility,snaptest
    - scripts/ci/lcov_to_coverage.sh coverage/lcov.info
    - flutter pub global run junitreport:tojunit --input coverage/widget_tests.json --output coverage/widget_tests.xml
  coverage: '/Coverage: \d+(?:\.\d+)?%/'
  artifacts:
    name: "test_widgets_coverage"
    when: always
    expose_as: "Widget test coverage"
    paths:
      - coverage/lcov.info
    reports:
      junit: coverage/widget_tests.xml

build_development:
  stage: build
  trigger:
    include: 
      - local: .gitlab/ci/build/*.yml
        inputs:
          environment: development
    strategy: mirror
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - ".gitlab/ci/build/*.yml"

build_versioning:
  stage: build 
  before_script:
    - scripts/ci/semver.sh -d
  script:
    - 'NEW_VERSION=$(scripts/ci/semver.sh -s | sed "s/New version: //")'
    - echo "NEW_VERSION=$NEW_VERSION" > new_version.env
  artifacts:
    name: "build_versioning"
    access: "none"
    paths:
      - pubspec.yaml
    reports:
      dotenv:
        new_version.env
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

build_production:
  stage: build
  needs:
    - job: build_versioning
      artifacts: true
  trigger:
    include: 
      - local: .gitlab/ci/build/*.yml
        inputs:
          environment: production
    strategy: mirror
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/cli:latest
  dependencies: [build_versioning]
  variables:
    GIT_AUTHOR_NAME: "$GITLAB_USER_NAME (automated)"
    GIT_AUTHOR_EMAIL: $GITLAB_USER_EMAIL
    GIT_COMMITTER_NAME: "$GITLAB_USER_NAME (automated)"
    GIT_COMMITTER_EMAIL: $GITLAB_USER_EMAIL
  script: |
    git add pubspec.yaml
    git commit -m "chore: bump version to ${NEW_VERSION}"
    git tag "$NEW_VERSION"
    git remote set-url origin "$CI_REPOSITORY_URL"
    git push origin HEAD:"$CI_COMMIT_BRANCH" --tags
  release:
    tag_name: $NEW_VERSION
    description: 'Automated release'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
