name: asr_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Arial
      fonts:
        - asset: fonts/Arial/Arial Regular.ttf
        - asset: fonts/Arial/Arial Narrow Italic.ttf
          style: italic
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab/RobotoSlab-Regular.ttf
        - asset: fonts/RobotoSlab/RobotoSlab-Bold.ttf
          weight: 700
        - asset: fonts/RobotoSlab/RobotoSlab-ExtraBold.ttf
          weight: 900
